### ISSUE TITLE
skewed input from checkTransferStatus

### ISSUE THREAD

**Issue by areinsvo** [CMSCompOps/WmAgentScripts#209] opened 2017-02-27 15:24 UTC
We've had messages like the following from stagor recently and again today.
Ending stagor because of skewed input from checkTransferStatus 

According to @vlimant, this means one of the transfer checks is failing because a transfer has been made on top of an existing subscription. We need to look into checkTransferStatus to make sure things are being handled sensibly and to see why the extra transfer request is being made.

**Comment by vlimant** [comment] 2017-02-27 15:49
the source of the issue is when unified gets to make a transfer request for a dataset that is already in place, leaving the transfer request with no subscription and impossible to know where the transfer is at.
One solution is to have checkTransferStatus report no completion to all site and items that were requested see https://cmsweb.cern.ch/phedex/datasvc/json/prod/transferrequests?request=947418 api, so that it does not just die there : sending a critical message nonetheless.

The issue originates from transferor that does not recognize properly the location and destination for a give dataset, and whatever is implemented in getDatasetDestinations is not correct ; I have modified it a bit to make more sense, but https://github.com/dmwm/PHEDEX/issues/1079 is in the way of anything and will make things crash for big datasets ...

**Comment by areinsvo** [comment] 2017-03-01 15:23
There is an error on the Unified critical page for getDatasetDestinations: "Failed the new implementation". Can you look into this? 

Are errors like "Performing spurious transfer check on 954532" also related to this issue?

**Comment by vlimant** [comment] 2017-03-01 15:34
Yes, there is a new implementation of getDatasetDestinations which was still failing on subscriptions query for the premix dataset, I added something today to try and bypass this.
Then subsequently stagor/stuckor/cachor fail on checking a ghost transfer request. : stagor is not sensitive to skewed checkTransferStatus anymore.

So getDatasetDestinations should not fail anymore, and things should get better

**Comment by areinsvo** [comment] 2017-03-09 15:32
The "Ending stagor because of skewed input from checkTransferStatus" message is back on the Unified critical page today for the first time since you made the changes. Can you look into why we got this message again?

**Comment by vlimant** [comment] 2017-03-09 16:17
that's because of 
https://cmsweb.cern.ch/phedex/prod/Request::View?request=960454
and https://github.com/dmwm/PHEDEX/issues/1079
It will show up there until task_HCA-PhaseIFall16GS-00007 and task_BPH-PhaseIFall16GS-00020 are not acquired

**Closed** 2017-07-18 17:16 UTC
