### ISSUE TITLE
Phedex2Rucio transition: Closing blocks of the input before assigning a workflow

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#668] opened 2020-09-30 12:57 UTC
**Is your feature request related to a problem? Please describe.**
Unified assignor module "closes" [1] the blocks of the input dataset before assigning a workflow using Phedex calls [2] We should decide on the fate of this functionality with the Phedex to Rucio transition.

[1] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/assignor.py#L221-L225
[2] https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L6362-L6391

**Describe the solution you'd like**
Honestly, I do not know what it means to close the blocks of a dataset. Since it's related to input, I thought it might be related to MSTransferor. @amaltaro @todor-ivanov Do you think this functionality is necessary? 

**Additional context**
@z4027163 @drkovalskyi FYI

**Comment by amaltaro** [comment] 2020-09-30 13:30
This is closing blocks in PhEDEx (and DBS) with a significant expensive algorithm. I'd just remove it and make sure that workflows get announced with blocks properly closed, thus relying on the WMAgent business.

**Comment by haozturk** [comment] 2020-10-01 08:03
Thanks for your comment Alan, that sounds like a good plan to me.

**Comment by vlimant** [comment] 2020-10-01 08:59
+1 on "thus relying on the WMAgent business". That feature of closing blocks is there exactly because WMAgent was not reliable in this matter. @amaltaro do you have the corresponding WMcore GH issue ? is there now a second round of closing properly everything at announce time?

**Comment by amaltaro** [comment] 2020-10-01 12:00
Blocks are never inserted in open status in DBS, so there is a place that this issue should never happened.
About blocks open in PhEDEx, I'd rather have those reported back such that we can try to investigate the issue and resolve it at the root cause, without having the need to keep hacks around forever. Of course, there isn't much we can do if we only spot an open block months after it was produced, all the logs are gone by then.

Anyhow, we are about to transition to Rucio, data gets injected with a completely new component. So it could be that this issue will never pop up again. Only way to know that, is by not having this workaround in Unified.

**Comment by vlimant** [comment] 2020-10-02 07:08
https://github.com/dmwm/WMCore/issues/9031

**Comment by vlimant** [comment] 2020-10-02 07:11
fingers crossed such issues with Rucio will be solved faster than the ones with Phedex

**Closed** 2020-10-06 19:26 UTC
Labels: question
